---
- hosts: localhost
  tasks: 
#     - name: Run the pwd command with built in
#       ansible.builtin.command: pwd
     - name: Run the pwd command
       shell: pwd
       register: output1 
     - debug :   
         var: output1.stdout_lines

     - name: Run the ls command
       shell: ls 
       register: output1 
     - debug :
         var: output1.stdout_lines

     - name: Make dir pratice
       shell: mkdir pratice 

     - name: create a file1 
       shell: touch file1.txt
   
     - name: Listlist contents
       shell: ls > file1.txt

     - name: writing to file1.txt
       shell: echo 'write something into file1' >> file1.txt  

     - name: checking the localhost dir   
       shell: echo {{ansible_playbook_python}} >> file1.txt




#- hosts: localhost
#  tasks:
#    - name: Save the result of 'whoami' in 'whoami_out'
#      ansible.builtin.command: whoami
#      register: whoami_out

    # - name: Return motd to registered var
    #   shell: cat /etc/motd
    #   register: mymotd

